version: '3.7'

services:
  app:
    image: metridoc
    environment:
      PASSENGER_APP_ENV: ${RAILS_ENV}
      RAILS_ENV:
    ports:
      - '80:80'
    secrets:
      - source: metridoc_rails_db_config
        target: /home/app/webapp/config/database.yml
        uid: '9999'
        gid: '9999'
        mode: 0440
      - source: metridoc_rails_secrets_config
        target: /home/app/webapp/config/secrets.yml
        uid: '9999'
        gid: '9999'
        mode: 0440
  db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/metridoc_db_password
    secrets:
      - metridoc_db_password
    volumes:
      - db_data:/var/lib/postgresql/data

secrets:
  metridoc_db_password:
    external: true
  metridoc_rails_db_config:
    external: true
  metridoc_rails_secrets_config:
    external: true

volumes:
  db_data:
