load_sequence:         5.0
target_model:          "Keyserver::Computer"
adapter:               'console_command'
commands:
  - "rm -rf /tmp/Computers.csv.tmp"
  - "rm -rf /tmp/Computers.cleaned.csv.tmp"
  - "mv /Users/erhanberber/development/NM/docs/metridoc/keyserverexport11082016/Computers.csv /tmp/Computers.csv.tmp"
  - "tr -d '\\0' < /tmp/Computers.csv.tmp > /tmp/Computers.cleaned.csv.tmp "
  - "rm -rf /Users/erhanberber/development/NM/docs/metridoc/keyserverexport11082016/Computers.csv"
  - "mv /tmp/Computers.cleaned.csv.tmp /Users/erhanberber/development/NM/docs/metridoc/keyserverexport11082016/Computers.csv"
