---
institution_code: 'DARTMOUTH'
host:             '<%= ENV["DARTMOUTH_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["DARTMOUTH_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["DARTMOUTH_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["DARTMOUTH_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["DARTMOUTH_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          5000
export_folder:    '/tmp/dartmouth_illiad/'
batch_size:       10000




