load_sequence:         2

# Source Config
source_adapter:        mssql
source_table:          "id_holdings"
column_mappings:
  "id_holdings.request_number": request_number
  "id_holdings.holdings_seq": holdings_seq
  "id_holdings.supplier_code": supplier_code
  "id_holdings.call_number": call_number
  "d.date_processed": process_date
join_tables:
  - "LEFT JOIN id_delivery d WITH (NOLOCK) ON id_holdings.request_number = d.request_number"
filters:
  - "id_holdings.call_number IS NOT NULL"
export_file_name:      "call_numbers.csv"

# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::CallNumber"
truncate_before_load:  "yes"
legacy_filter_date_field: "process_date"
