load_sequence:         3

# Source Config
source_adapter:        mssql
source_table:          "id_audit"
column_mappings:
  "id_audit.request_number": request_number
  "id_audit.time_stamp": print_date
  "id_audit.note": note
  "d.date_processed": process_date
  "c.catalog_library_id": library_id
join_tables:
  - "LEFT JOIN id_delivery d ON id_audit.request_number = d.request_number"
  - "LEFT JOIN id_catalog_code c ON catalog_code_desc = replace(id_audit.note,'Printed At: ','')"
filters:
  - "id_audit.stat_location": "8"
export_file_name:      "print_dates.csv"
export_filter_date_sql: "id_audit.time_stamp > ?"
export_filter_date_range_sql: "id_audit.time_stamp > ? AND id_audit.time_stamp < ?"


# Target Config
target_adapter:        csv
target_model:          "Borrowdirect::PrintDate"
purge_legacy_data_before_load:  "yes"
legacy_filter_date_field: "print_date"
