---
institution_code: 'HARVARD'
host:             '<%= ENV["HARVARD_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["HARVARD_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["HARVARD_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["HARVARD_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["HARVARD_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          5000
tds_version:      7.3
export_folder:    '/tmp/harvard_illiad/'
batch_size:       10000
