load_sequence:         6

# Source Config
source_adapter:        mssql
source_table:          "id_patron_type"
column_mappings:
  patron_type: patron_type
  patron_type_desc: patron_type_desc
export_file_name:      "patron_types.csv"

# Target Config
target_adapter:        csv
target_model:          "Ezborrow::PatronType"
purge_legacy_data_before_load:  "yes"
