---
institution_code: 'UPENN'
adapter:          'sqlserver'
host:             ENV["UPENN_EZBORROW_MSSQL_HOST"]
port:             ENV["UPENN_EZBORROW_MSSQL_PORT"]
database:         ENV["UPENN_EZBORROW_MSSQL_DB"]
username:         ENV["UPENN_EZBORROW_MSSQL_UID"]
password:         ENV["UPENN_EZBORROW_MSSQL_PWD"]
pool:             5
timeout:          5000
