---
config_dir: /opt/metridoc
alertmanager_slack_api_url: "http://localhost"
database_subnet: 10.0.2.0/24
ezpaarse_mongodb_password: "{{ vault_ezpaarse_mongodb_password }}"
ezpaarse_mongodb_username: "{{ vault_ezpaarse_mongodb_username }}"
ezpaarse_mongodb_root_password: "{{ vault_ezpaarse_mongodb_root_password }}"
ezpaarse_mongodb_root_username: "{{ vault_ezpaarse_mongodb_root_username }}"
ezpaarse_nfs_input_volume_address: "{{ vault_ezpaarse_nfs_input_volume_address }}"
ezpaarse_nfs_input_volume_device: "{{ vault_ezpaarse_nfs_input_volume_device }}"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_database_password: "{{ vault_grafana_database_password }}"
libwizard_client_id: "{{ vault_libwizard_client_id }}"
libwizard_client_secret: "{{ vault_libwizard_client_secret }}"
libwizard_base_url: "{{ vault_libwizard_base_url }}"
monitoring_subnet: 10.0.10.0/24
postgres_database_password: "{{ vault_postgres_database_password }}"
postgres_monitoring_password: "{{ vault_postgres_monitoring_password }}"
postgres_replication_password: "{{ vault_postgres_replication_password }}"
rails_secret_key_base: "{{ vault_rails_secret_key_base }}"
rails_app_user_gid: 1000
rails_app_user_uid: 1000
saml_email_attribute: "{{ vault_saml_email_attribute }}"
saml_first_name_attribute: "{{ vault_saml_first_name_attribute }}"
saml_last_name_attribute: "{{ vault_saml_last_name_attribute }}"
saml_logout_url: "{{ vault_saml_logout_url }}"

alertmanager_1_swarm_node: metridoc-manager
alertmanager_2_swarm_node: metridoc-manager
ezpaarse_swarm_node: metridoc-manager
jenkins_swarm_node: metridoc-manager
metridoc_swarm_node: metridoc-manager
postgres_primary_swarm_node: metridoc-manager
postgres_replica_swarm_node: metridoc-manager

proxy:
  ssl:
    crt:
      location: "/etc/ssl/proxy.crt"
    key:
      location: "/etc/ssl/proxy.key"

# Docker config / secret versions
alertmanager_config_version: v2
alertmanager_templates_version: v2
ezpaarse_config_version: v1
ezpaarse_mongodb_password_version: v1
ezpaarse_mongodb_username_version: v1
ezpaarse_mongodb_root_password_version: v1
ezpaarse_mongodb_root_username_version: v1
grafana_admin_password_version: v1
grafana_dashboards_version: v1
grafana_dashboard_home_version: v1
grafana_dashboard_postgres_version: v1
grafana_database_password_version: v1
grafana_database_pg_hba_conf_version: v1
grafana_datasources_version: v1
node_exporter_entrypoint_version: v1
postgres_database_password_version: v1
postgres_exporter_queries_version: v1
postgres_init_primary_version: v1
postgres_monitoring_password_version: v1
postgres_pgpass_version: v1
postgres_primary_pg_hba_conf_version: v1
postgres_replica_pg_hba_conf_version: v1
postgres_start_replica_version: v1
prometheus_alerts_version: v1
prometheus_config_version: v1
python_jobs_database_secret_version: v1
python_jobs_libwizard_secret_version: v1
rails_database_config_version: v1
rails_secrets_config_version: v1

docker_stack_env:
  ALERTMANAGER_1_EXTERNAL_URL: http://{{ alertmanager_1_swarm_node }}.library.upenn.int:9093
  ALERTMANAGER_2_EXTERNAL_URL: http://{{ alertmanager_2_swarm_node }}.library.upenn.int:9094
  APP_USER_GID: "{{ rails_app_user_gid }}"
  APP_USER_UID: "{{ rails_app_user_uid }}"
  DATABASE_SUBNET: "{{ database_subnet }}"
  EZPAARSE_IMAGE_TAG: "main"
  EZPAARSE_MONGODB_IMAGE_TAG: "main"
  GF_SERVER_ROOT_URL: http://mdoc-dev.library.upenn.int:3000
  GF_SMTP_HOST: "{{ vault_grafana_smtp_host }}"
  JENKINS_IMAGE_TAG: main
  MAILER_DEFAULT_FROM: "{{ vault_mailer_default_from }}"
  MAILER_DOMAIN: "{{ vault_mailer_domain }}"
  MAILER_HOST: "{{ vault_mailer_host }}"
  METRIDOC_IMAGE_TAG: "master"
  METRIDOC_REPLICAS: 1
  MONITORING_SUBNET: "{{ monitoring_subnet }}"
  PROMETHEUS_REPLICAS: 1
  PYTHON_JOBS_IMAGE_TAG: "main"
  PYTHON_JOBS_REPLICAS: 1
  RAILS_ENV: development

  ALERTMANAGER_CONFIG_VERSION: "{{ alertmanager_config_version }}"
  ALERTMANAGER_TEMPLATES_VERSION: "{{ alertmanager_templates_version }}"
  EZPAARSE_CONFIG_VERSION: "{{ ezpaarse_config_version }}"
  EZPAARSE_MONGODB_PASSWORD_VERSION: "{{ ezpaarse_mongodb_password_version }}"
  EZPAARSE_MONGODB_USERNAME_VERSION: "{{ ezpaarse_mongodb_username_version }}"
  EZPAARSE_MONGODB_ROOT_PASSWORD_VERSION: "{{ ezpaarse_mongodb_root_password_version }}"
  EZPAARSE_MONGODB_ROOT_USERNAME_VERSION: "{{ ezpaarse_mongodb_root_username_version }}"
  GRAFANA_ADMIN_PASSWORD_VERSION: "{{ grafana_admin_password_version }}"
  GRAFANA_DASHBOARDS_VERSION: "{{ grafana_dashboards_version }}"
  GRAFANA_DASHBOARD_HOME_VERSION: "{{ grafana_dashboard_home_version }}"
  GRAFANA_DASHBOARD_POSTGRES_VERSION: "{{ grafana_dashboard_postgres_version }}"
  GRAFANA_DATABASE_PASSWORD_VERSION: "{{ grafana_database_password_version }}"
  GRAFANA_DATABASE_PG_HBA_CONF_VERSION: "{{ grafana_database_pg_hba_conf_version }}"
  GRAFANA_DATASOURCES_VERSION: "{{ grafana_datasources_version }}"
  NODE_EXPORTER_ENTRYPOINT_VERSION: "{{ node_exporter_entrypoint_version }}"
  POSTGRES_DATABASE_PASSWORD_VERSION: "{{ postgres_database_password_version }}"
  POSTGRES_EXPORTER_QUERIES_VERSION: "{{ postgres_exporter_queries_version }}"
  POSTGRES_INIT_PRIMARY_VERSION: "{{ postgres_init_primary_version }}"
  POSTGRES_MONITORING_PASSWORD_VERSION: "{{ postgres_monitoring_password_version }}"
  POSTGRES_PGPASS_VERSION: "{{ postgres_pgpass_version }}"
  POSTGRES_PRIMARY_PG_HBA_CONF_VERSION: "{{ postgres_primary_pg_hba_conf_version }}"
  POSTGRES_REPLICA_PG_HBA_CONF_VERSION: "{{ postgres_replica_pg_hba_conf_version }}"
  POSTGRES_START_REPLICA_VERSION: "{{ postgres_start_replica_version }}"
  PROMETHEUS_ALERTS_VERSION: "{{ prometheus_alerts_version }}"
  PROMETHEUS_CONFIG_VERSION: "{{ prometheus_config_version }}"
  PYTHON_JOBS_DATABASE_SECRET_VERSION: "{{ python_jobs_database_secret_version }}"
  PYTHON_JOBS_LIBWIZARD_SECRET_VERSION: "{{ python_jobs_libwizard_secret_version }}"
  RAILS_DATABASE_CONFIG_VERSION: "{{ rails_database_config_version }}"
  RAILS_SECRETS_CONFIG_VERSION: "{{ rails_secrets_config_version }}"
  SAML_EMAIL_ATTRIBUTE: "{{ saml_email_attribute }}"
  SAML_FIRST_NAME_ATTRIBUTE: "{{ saml_first_name_attribute }}"
  SAML_LAST_NAME_ATTRIBUTE: "{{ saml_last_name_attribute }}"
  SAML_LOGOUT_URL: "{{ saml_logout_url }}"

  ALMA_API_KEY: "{{ vault_alma_api_key }}"

  SPRINGSHARE_LIBCAL_ID: "{{ vault_springshare_libcal_id }}"
  SPRINGSHARE_LIBCAL_SECRET: "{{ vault_springshare_libcal_secret }}"
  SPRINGSHARE_LIBCAL_GRANTTYPE: "{{ vault_springshare_libcal_granttype }}"

  BORROWDIRECT_RESHARE_DB: "{{ vault_borrowdirect_reshare_db }}"
  BORROWDIRECT_RESHARE_HOST: "{{ vault_borrowdirect_reshare_host }}"
  BORROWDIRECT_RESHARE_PORT: "{{ vault_borrowdirect_reshare_port }}"
  BORROWDIRECT_RESHARE_PWD: "{{ vault_borrowdirect_reshare_pwd }}"
  BORROWDIRECT_RESHARE_UID: "{{ vault_borrowdirect_reshare_uid }}"

  COLUMBIA_ILLIAD_MSSQL_DB: "{{ vault_columbia_illiad_mssql_db }}"
  COLUMBIA_ILLIAD_MSSQL_HOST: "{{ vault_columbia_illiad_mssql_host }}"
  COLUMBIA_ILLIAD_MSSQL_PORT: "{{ vault_columbia_illiad_mssql_port }}"
  COLUMBIA_ILLIAD_MSSQL_PWD: "{{ vault_columbia_illiad_mssql_pwd }}"
  COLUMBIA_ILLIAD_MSSQL_UID: "{{ vault_columbia_illiad_mssql_uid }}"

  CORNELL_ILLIAD_MSSQL_DB: "{{ vault_cornell_illiad_mssql_db }}"
  CORNELL_ILLIAD_MSSQL_HOST: "{{ vault_cornell_illiad_mssql_host }}"
  CORNELL_ILLIAD_MSSQL_PORT: "{{ vault_cornell_illiad_mssql_port }}"
  CORNELL_ILLIAD_MSSQL_PWD: "{{ vault_cornell_illiad_mssql_pwd }}"
  CORNELL_ILLIAD_MSSQL_UID: "{{ vault_cornell_illiad_mssql_uid }}"

  DARTMOUTH_ILLIAD_MSSQL_DB: "{{ vault_dartmouth_illiad_mssql_db }}"
  DARTMOUTH_ILLIAD_MSSQL_HOST: "{{ vault_dartmouth_illiad_mssql_host }}"
  DARTMOUTH_ILLIAD_MSSQL_PORT: "{{ vault_dartmouth_illiad_mssql_port }}"
  DARTMOUTH_ILLIAD_MSSQL_PWD: "{{ vault_dartmouth_illiad_mssql_pwd }}"
  DARTMOUTH_ILLIAD_MSSQL_UID: "{{ vault_dartmouth_illiad_mssql_uid }}"

  DUKE_ILLIAD_MSSQL_DB: "{{ vault_duke_illiad_mssql_db }}"
  DUKE_ILLIAD_MSSQL_HOST: "{{ vault_duke_illiad_mssql_host }}"
  DUKE_ILLIAD_MSSQL_PORT: "{{ vault_duke_illiad_mssql_port }}"
  DUKE_ILLIAD_MSSQL_PWD: "{{ vault_duke_illiad_mssql_pwd }}"
  DUKE_ILLIAD_MSSQL_UID: "{{ vault_duke_illiad_mssql_uid }}"

  HARVARD_ILLIAD_MSSQL_DB: "{{ vault_harvard_illiad_mssql_db }}"
  HARVARD_ILLIAD_MSSQL_HOST: "{{ vault_harvard_illiad_mssql_host }}"
  HARVARD_ILLIAD_MSSQL_PORT: "{{ vault_harvard_illiad_mssql_port }}"
  HARVARD_ILLIAD_MSSQL_PWD: "{{ vault_harvard_illiad_mssql_pwd }}"
  HARVARD_ILLIAD_MSSQL_UID: "{{ vault_harvard_illiad_mssql_uid }}"

  MIT_ILLIAD_MSSQL_DB: "{{ vault_mit_illiad_mssql_db }}"
  MIT_ILLIAD_MSSQL_HOST: "{{ vault_mit_illiad_mssql_host }}"
  MIT_ILLIAD_MSSQL_PORT: "{{ vault_mit_illiad_mssql_port }}"
  MIT_ILLIAD_MSSQL_PWD: "{{ vault_mit_illiad_mssql_pwd }}"
  MIT_ILLIAD_MSSQL_UID: "{{ vault_mit_illiad_mssql_uid }}"

  PRINCETON_ILLIAD_MSSQL_DB: "{{ vault_princeton_illiad_mssql_db }}"
  PRINCETON_ILLIAD_MSSQL_HOST: "{{ vault_princeton_illiad_mssql_host }}"
  PRINCETON_ILLIAD_MSSQL_PORT: "{{ vault_princeton_illiad_mssql_port }}"
  PRINCETON_ILLIAD_MSSQL_PWD: "{{ vault_princeton_illiad_mssql_pwd }}"
  PRINCETON_ILLIAD_MSSQL_UID: "{{ vault_princeton_illiad_mssql_uid }}"

  RESHARE_DB: "{{ vault_reshare_db }}"
  RESHARE_HOST: "{{ vault_reshare_host }}"
  RESHARE_PORT: "{{ vault_reshare_port }}"
  RESHARE_PWD: "{{ vault_reshare_pwd }}"
  RESHARE_UID: "{{ vault_reshare_uid }}"

  UPENN_BORROWDIRECT_MSSQL_DB: "{{ vault_upenn_borrowdirect_mssql_db }}"
  UPENN_BORROWDIRECT_MSSQL_HOST: "{{ vault_upenn_borrowdirect_mssql_host }}"
  UPENN_BORROWDIRECT_MSSQL_PORT: "{{ vault_upenn_borrowdirect_mssql_port }}"
  UPENN_BORROWDIRECT_MSSQL_PWD: "{{ vault_upenn_borrowdirect_mssql_pwd }}"
  UPENN_BORROWDIRECT_MSSQL_UID: "{{ vault_upenn_borrowdirect_mssql_uid }}"

  UPENN_EZBORROW_MSSQL_DB: "{{ vault_upenn_ezborrow_mssql_db }}"
  UPENN_EZBORROW_MSSQL_HOST: "{{ vault_upenn_ezborrow_mssql_host }}"
  UPENN_EZBORROW_MSSQL_PORT: "{{ vault_upenn_ezborrow_mssql_port }}"
  UPENN_EZBORROW_MSSQL_PWD: "{{ vault_upenn_ezborrow_mssql_pwd }}"
  UPENN_EZBORROW_MSSQL_UID: "{{ vault_upenn_ezborrow_mssql_uid }}"

  UPENN_GATECOUNT_SFTP_HOST: "{{ vault_upenn_gatecount_sftp_host }}"
  UPENN_GATECOUNT_SFTP_PWD: "{{ vault_upenn_gatecount_sftp_pwd }}"
  UPENN_GATECOUNT_SFTP_USER: "{{ vault_upenn_gatecount_sftp_user }}"

  UPENN_ILLIAD_MSSQL_DB: "{{ vault_upenn_illiad_mssql_db }}"
  UPENN_ILLIAD_MSSQL_HOST: "{{ vault_upenn_illiad_mssql_host }}"
  UPENN_ILLIAD_MSSQL_PORT: "{{ vault_upenn_illiad_mssql_port }}"
  UPENN_ILLIAD_MSSQL_PWD: "{{ vault_upenn_illiad_mssql_pwd }}"
  UPENN_ILLIAD_MSSQL_UID: "{{ vault_upenn_illiad_mssql_uid }}"

  YALE_ILLIAD_MSSQL_DB: "{{ vault_yale_illiad_mssql_db }}"
  YALE_ILLIAD_MSSQL_HOST: "{{ vault_yale_illiad_mssql_host }}"
  YALE_ILLIAD_MSSQL_PORT: "{{ vault_yale_illiad_mssql_port }}"
  YALE_ILLIAD_MSSQL_PWD: "{{ vault_yale_illiad_mssql_pwd }}"
  YALE_ILLIAD_MSSQL_UID: "{{ vault_yale_illiad_mssql_uid }}"
