---
institution_code: 'STANFORD'
host:             '<%= ENV["STANFORD_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["STANFORD_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["STANFORD_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["STANFORD_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["STANFORD_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          120000
export_folder:    '/tmp/stanford_illiad/'
batch_size:       10000
