---
institution_code: 'STANFORD'
host:             '<%= ENV["STANFORD_ILLIAD_MSSQL_HOST"] %>'
port:             '<%= ENV["STANFORD_ILLIAD_MSSQL_PORT"] %>'
database:         '<%= ENV["STANFORD_ILLIAD_MSSQL_DB"]   %>'
username:         '<%= ENV["STANFORD_ILLIAD_MSSQL_UID"]  %>'
password:         '<%= ENV["STANFORD_ILLIAD_MSSQL_PWD"]  %>'
pool:             5
timeout:          5000
tds_version:      7.3
export_folder:    '/tmp/stanford_illiad/'
import_folder:    '/Users/jkiser/Desktop/illiadstanford'
batch_size:       10000
