load_sequence:         14
target_adapter:        'native_sql'
target_model:          "Illiad::Tracking"
purge_legacy_data_before_load:  "no"
sql: |
                        UPDATE illiad_trackings
                        SET turnaround_req_rec = DATE_PART('day', receive_date - request_date) ,
                            turnaround_req_shp = DATE_PART('day', ship_date - request_date) ,
                            turnaround_shp_rec = DATE_PART('day', receive_date - ship_date) 
                        WHERE institution_id = %{institution_id}
                        ;
